"""init schema

Revision ID: 3a9801ca256a
Revises:
Create Date: 2026-05-16 13:00:24.967022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a9801ca256a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=8), nullable=True),
        sa.Column("sex", sa.String(length=16), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("activity", sa.String(length=16), nullable=True),
        sa.Column("goal", sa.String(length=16), nullable=True),
        sa.Column("tdee_kcal", sa.Integer(), nullable=True),
        sa.Column("target_protein_g", sa.Integer(), nullable=True),
        sa.Column("target_fat_g", sa.Integer(), nullable=True),
        sa.Column("target_carbs_g", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id", name="uq_users_telegram_id"),
    )
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=False
    )
    op.create_table(
        "foods",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("brand", sa.String(length=128), nullable=True),
        sa.Column("barcode", sa.String(length=32), nullable=True),
        sa.Column("cuisine", sa.String(length=16), nullable=True),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("kcal", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("piece_weight_g", sa.Float(), nullable=True),
        sa.Column(
            "servings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_foods_brand", "foods", ["brand"], unique=False)
    op.create_index("ix_foods_name", "foods", ["name"], unique=False)
    op.create_index("uq_foods_barcode", "foods", ["barcode"], unique=True)
    op.create_table(
        "meals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("meal_type", sa.String(length=16), nullable=False),
        sa.Column("eaten_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=True),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_meals_user_type_eaten",
        "meals",
        ["user_id", "meal_type", "eaten_at"],
        unique=False,
    )
    op.create_index(
        "uq_meals_user_tg_msg",
        "meals",
        ["user_id", "tg_message_id"],
        unique=True,
        postgresql_where="tg_message_id IS NOT NULL",
    )
    op.create_table(
        "meal_items",
        sa.Column("meal_id", sa.UUID(), nullable=False),
        sa.Column("food_name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("weight_g", sa.Float(), nullable=False),
        sa.Column("kcal", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("food_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meal_items_food_name"), "meal_items", ["food_name"], unique=False
    )
    op.create_index(
        op.f("ix_meal_items_meal_id"), "meal_items", ["meal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meal_items_meal_id"), table_name="meal_items")
    op.drop_index(op.f("ix_meal_items_food_name"), table_name="meal_items")
    op.drop_table("meal_items")
    op.drop_index(
        "uq_meals_user_tg_msg",
        table_name="meals",
        postgresql_where="tg_message_id IS NOT NULL",
    )
    op.drop_index("ix_meals_user_type_eaten", table_name="meals")
    op.drop_table("meals")
    op.drop_index("uq_foods_barcode", table_name="foods")
    op.drop_index("ix_foods_name", table_name="foods")
    op.drop_index("ix_foods_brand", table_name="foods")
    op.drop_table("foods")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
